### PR TITLE
Updated sample sketches

### PR DESCRIPTION
**Pull request by EmbeddedMan**
I only meant to change dim.ino, hellodotstar.ino and hellodotstarBug.ino, but it looks like a ton of other stuff got changed for some reason. I can't figure out how to easily undo that - maybe you can figure it out Rick.

In any case, I fixed dim.ino so it uses SoftPWMServo, made hellodostar more exciting, and created a 'buggy' version for the advanced class to show debugging in MPLAB X.

### CODE REVIEW

**Comment by ricklon** [comment]
I'll check and see. Sometimes doing a commit that includes the files you want by name would work best.

**Comment by EmbeddedMan** [comment]
Yes, I agree. That would have been a better way to go in this case. Sorry
if this causes problems for you - my git-fu is not strong enough. I'm happy
to back it out and re-do if that would make it easier on you.

*Brian

**Comment by ricklon** [comment]
Shoot. I jumped ahead a merged on my phone. I should have looked first. I've got undo this. Sorry.

**Comment by EmbeddedMan** [comment]
No problem at all Rick. I'll fix and resubmit tonight. Sorry for the
trouble!

*Brian

**Pull request merged**
